# Caelestis - Kitty

# Font
font_family  JetBrains Mono Light
font_size    12.0

# Window
background           #FCFAF6
foreground           #4169E1

cursor               #4682B4
cursor_text_color    #6496ED

selection_background #4682B4
selection_foreground #B0C4DE

# Cursor
cursor_shape block
cursor_blink_interval 0.5

# Scrollback
scrollback_lines 10000

